package com.arunrk.notes.domain.model

import java.time.Instant
import java.util.UUID

enum class DevicePlatform {
    ANDROID,
    IOS,
    DESKTOP,
    UNKNOWN;

    companion object {
        /**
         * Never throws. An unrecognised platform header is a cosmetic problem
         * (it only affects conflict-copy labels and session lists) and must not
         * be able to fail a login.
         */
        fun parse(raw: String?): DevicePlatform =
            entries.firstOrNull { it.name.equals(raw?.trim(), ignoreCase = true) } ?: UNKNOWN
    }
}

/**
 * A client installation. The id is generated by the client and is stable for
 * the lifetime of the install.
 */
data class Device(
    val id: UUID,
    val userId: UUID,
    val platform: DevicePlatform,
    val displayName: String? = null,
    val appVersion: String? = null,
    val lastSeenAt: Instant,
    val createdAt: Instant,
)
