package com.arunrk.notes.domain.model

import com.arunrk.notes.common.hash.Hashing
import java.time.Instant
import java.util.UUID

enum class NoteContentType {
    PLAIN,
    MARKDOWN,
    RICH;

    companion object {
        fun parse(raw: String?): NoteContentType =
            entries.firstOrNull { it.name.equals(raw?.trim(), ignoreCase = true) } ?: PLAIN
    }
}

enum class NoteSortOrder {
    UPDATED_DESC,
    CREATED_DESC,
    TITLE_ASC;

    companion object {
        fun parse(raw: String?): NoteSortOrder =
            entries.firstOrNull { it.name.equals(raw?.trim(), ignoreCase = true) } ?: UPDATED_DESC
    }
}

/**
 * A note as the server holds it.
 *
 * [id] is generated by the client so notes can be created offline without a
 * round trip. [version] and [changeSeq] are server-owned and are the two values
 * the whole synchronisation design rests on:
 *
 *  - [version] is the optimistic-concurrency precondition. A push carries the
 *    version it was derived from; a mismatch means someone else wrote first.
 *  - [changeSeq] is this user's monotonic cursor position, assigned under a row
 *    lock so that sequence order equals commit order.
 *
 * [clientCreatedAt] / [clientUpdatedAt] are the device's own wall clock. They
 * are shown to the user and used only as a last-resort tie-break; they never
 * decide ordering, because device clocks are wrong and user-settable.
 */
data class Note(
    val id: UUID,
    val userId: UUID,

    val title: String,
    val content: String,
    val contentType: NoteContentType = NoteContentType.PLAIN,
    val color: String? = null,
    val isPinned: Boolean = false,
    val isArchived: Boolean = false,
    val isDeleted: Boolean = false,
    val sortIndex: Double? = null,

    val clientCreatedAt: Instant,
    val clientUpdatedAt: Instant,
    val createdAt: Instant,
    val updatedAt: Instant,
    val deletedAt: Instant? = null,

    val version: Long,
    val changeSeq: Long,
    val contentHash: String,

    val lastModifiedBy: UUID? = null,
    /** Set on a conflict copy; points at the note it diverged from. */
    val conflictOf: UUID? = null,
) {
    val isActive: Boolean get() = !isDeleted

    companion object {
        fun hashOf(title: String, content: String): String = Hashing.noteContentHash(title, content)
    }
}

/** A page of results plus the total, for the paginated REST endpoints. */
data class PageResult<T>(
    val items: List<T>,
    val page: Int,
    val size: Int,
    val totalElements: Long,
) {
    val totalPages: Int
        get() = if (size <= 0) 0 else ((totalElements + size - 1) / size).toInt()

    val hasNext: Boolean get() = (page + 1) * size.toLong() < totalElements
}
